import Header from "@/app/Header";
import "../styles/app.scss";
import { Inter } from "next/font/google";
import { ContextProvider } from "@/Components/Client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo APP",
  description: "Generated by Arvind Kumar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Header />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
